CREATE TABLE GenericUser (
  UserId VARCHAR(50) NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  lastname VARCHAR(50) NOT NULL,
  birthday VARCHAR(20) DEFAULT NULL,
  email VARCHAR(100) NOT NULL,
  gender VARCHAR(2) NOT NULL,
  nickname VARCHAR(100) NOT NULL,
  salt VARCHAR(100) NOT NULL,
  composedSecret VARCHAR(256) NOT NULL,
  lastLogin VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (UserId)
);

CREATE TABLE Characters ( --manca il riferimento al'id del genericUser
  CHARACTER_ID NUMBER PRIMARY KEY,
  CHARACTER_NAME VARCHAR(50) NOT NULL,
  CHARACTER_ICON VARCHAR(250) NOT NULL,
  gender VARCHAR(10) NOT NULL,
  status VARCHAR(15) NOT NULL,
  clevel NUMBER NOT NULL,
  experience NUMBER NOT NULL,
  TOTAL_EXPERIENCE NUMBER NOT NULL,
  health NUMBER NOT NULL,
  HEALTH_STATUS VARCHAR(20) NOT NULL,
  role VARCHAR(20) NOT NULL, --diverso dal roleId (admin ecc..profili abilitativi)
  PRIMARY KEY (CHARACTER_ID)
);
CREATE TABLE CharactersHistory(
    CHISTORY_ID NUMBER PRIMARY KEY,
    history VARCHAR(500)
);
CREATE TABLE CharactersDescription(
    DESCRIPTION_ID NUMBER PRIMARY KEY,
    description VARCHAR(500)
);
CREATE TABLE CharactersStatistics(
    CHARACTER_ID NUMBER PRIMARY KEY NOT NULL,
    forza NUMBER NOT NULL,
    destrezza NUMBER NOT NULL,
    costituzione NUMBER NOT NULL,
    intelligenza NUMBER NOT NULL,
    saggezza NUMBER NOT NULL
);

CREATE TABLE CharacterTemporaryEffect(
    id NUMBER NOT NULL AUTO_INCREMENT,
    CHARACTER_ID NUMBER NOT NULL,
    modifier NUMBER NOT NULL,
    stat VARCHAR(15) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE Guild (
  GUILD_ID NUMBER NOT NULL,
  name VARCHAR(50) NOT NULL,
  description varchar(300),
  guild_img varchar(250),
  ATTIVO BIT,
  statute TEXT,
  announcement VARCHAR(500),
  PRIMARY KEY (GUILD_ID)
);
CREATE TABLE GUILDBANK (
GUILD_ID NUMBER PRIMARY KEY,
amount NUMBER,
PRIMARY KEY(GUILD_ID)
);

CREATE TABLE GUILDROLE (
ROLEID INT NOT NULL,
GUILDID INT NOT NULL,
NAME VARCHAR(50) NOT NULL,
SALARY INT NOT NULL,
MANAGER BIT NOT NULL,
ROLE_IMG VARCHAR(250),
DESCRIPTION VARCHAR(300),
GUILDLEVEL INT NOT NULL,
PRIMARY KEY (ROLEID,GUILDID)
);

CREATE TABLE GUILDMEMBER (
CHARACTER_ID NUMBER NOT NULL,
ROLE_ID NUMBER NOT NULL,
PRIMARY KEY(CHARACTER_ID,ROLE_ID)
);

CREATE VIEW V_GUILDMEMBERS
AS
SELECT
 GR.GUILDID AS GUILDID,
 GR.ROLEID AS ROLEID,
 CH.CHARACTER_ID AS CHARACTERID,
 CH.CHARACTER_NAME AS CHARACTER_NAME,
 GR.GUILDLEVEL AS GUILD_LEVEL,
 GR.NAME AS ROLE_NAME,
 GR.ROLE_IMG AS ROLE_IMG
FROM GUILDMEMBER GM
JOIN GUILDROLE GR
ON GM.ROLE_ID = GR.ROLEID
JOIN CHARACTERS AS CH
ON CH.CHARACTER_ID = GM.CHARACTER_ID;



CREATE TABLE CHARACTER_CV (
CHARACTER_ID INT NOT NULL,
ROLE_ID INT NOT NULL,
ENROLLMENT_DATE DATE
);

CREATE TABLE Chat(
    chatId NUMBER AUTO_INCREMENT NOT NULL,
    creationDate DATE NOT NULL,
    active BIT NOT NULL,
    idLuogo NUMBER NOT NULL,
    privateChat BIT NOT NULL,
    characterId NUMBER NOT NULL,
    expirationDate DATE NULL,
    fixed BIT NOT NULL,
    PRIMARY KEY (chatId)
);

CREATE TABLE ChatMembers(
    chatId NUMBER NOT NULL,
    characterId NUMBER NOT NULL
);

CREATE TABLE PresentiLuogo(
    idLuogo NUMBER NOT NULL,
    characterId NUMBER NOT NULL,
    available BIT NOT NULL,
    messaggio TEXT,
    PRIMARY KEY(idLuogo, characterId)
);

CREATE TABLE Luoghi(
    idLuogo NUMBER  NOT NULL AUTO_INCREMENT,
    descr VARCHAR(MAX),
    nomeLuogo VARCHAR(100),
    statoLuogo VARCHAR(100),
    immagine VARCHAR(200),
    PRIMARY KEY(idLuogo)
);

CREATE VIEW `V_PRESENTI` AS
SELECT
pres.idLuogo,loc.nomeLuogo,ch.CHARACTER_NAME as characterName,ch.CHARACTER_ID as characterId,ch.CHARACTER_ICON,pres.messaggio,pres.available
FROM
presentiluogo AS PRES
JOIN characters AS CH
on pres.characterId = ch.CHARACTER_ID
JOIN LUOGHI AS LOC
on pres.idLuogo = loc.idLuogo;

CREATE TABLE ChatMessages (
    ID NUMBER NOT NULL AUTO_INCREMENT,
    CHATID NUMBER  NOT NULL,
    cACTION VARCHAR(12) NOT NULL,
    CARICA VARCHAR(50),
    IMG VARCHAR(500),
    RECEIVER VARCHAR(100),
    SENDER VARCHAR(100) NOT NULL,
    CHARACTERID INT ,
    TAG VARCHAR (50),
    TESTO TEXT,
    CTIMESTAMP DOUBLE NOT NULL,
    TOOLTIP_CARICA VARCHAR NOT NULL
);

CREATE TABLE Inventory(
    CHARACTER_ID NUMBER NOT NULL,
    gold NUMBER,
    PRIMARY KEY(CHARACTER_ID)
);

CREATE TABLE InventoryObject(
    ITEM_ID NUMBER NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    description VARCHAR(50) NOT NULL,
    isEquipment BIT NOT NULL,
    isRare BIT NOT NULL,
    category VARCHAR(15) NOT NULL,
    bodyPart VARCHAR(15),
    duration NUMBER,
    url VARCHAR(500),
    PRIMARY KEY(ITEM_ID)
);

CREATE TABLE InventoryObjectEffect(
    effect_id INT NOT NULL,
    inventoryObjectId INT NOT NULL,
    healthStatus VARCHAR(15),
    healing INT,
    stat VARCHAR(15),
    isTemporary BIT,
    duration INT,
    isOneShot BIT,
    modifier INT
);

CREATE TABLE CharacterInventoryObject(
    idInventoryObject INT NOT NULL,
    characterId INT NOT NULL,
    quantity INT,
    inUse BIT,
    duration INT,
    acquiringDate DATE,
    acquiredBy INT,
    PRIMARY KEY(idInventoryObject, characterId)
);

CREATE TABLE DAILYEXP (
CHARACTERID INT,
DAILYEXP INT ,
EXPDATE DATE,
PRIMARY KEY (CHARACTERID,EXPDATE)
)

